### PR TITLE
Switch to more common installation variables

### PR DESCRIPTION
**Pull request by Begasus**

### CODE REVIEW

**Comment by Begasus** [comment]
Should be checked out, follow up for: https://github.com/texstudio-org/texstudio/issues/3124

**Comment by sunderme** [comment]
the recommendation is to use `include(GNUInstallDirs)` to predefine the paths.
Any reason not to use this here ?

**Comment by Begasus** [comment]
> the recommendation is to use `include(GNUInstallDirs)` to predefine the paths. Any reason not to use this here ?

Not directly, just haven't used it so far in any patches, I'll take a deeper look into this. Thanks for replying.

**Comment by Begasus** [comment]
Think this should do it, if not please comment :) (checked localy)

**Comment by sunderme** [comment]
thanks

**Comment by Begasus** [comment]
Thanks! Saves patching it for the next release :)

**Pull request merged**
