### PR TITLE
Fix detection of qtermwidget5 in qmake project file

### PR DESCRIPTION
**Pull request by MeanSquaredError**
This PR fixes the detection of qtermwidget5 on Fedora 31 (probably on other Linux distributions too).
It is expected to fix https://github.com/texstudio-org/texstudio/issues/1008

### CODE REVIEW

**Comment by sunderme** [comment]
the version detection does not work here.
pkg-config always exists with status 1.

**Comment by MeanSquaredError** [comment]
I updated the code so that texstudio.pro will log a bit of extra information just before it tries to detect qtermwidget5. If qtermwidget5 .pc file is present it should print the variable names (without the values) from the .pc file. Otherwise it should print some error message.

Can you please run qmake and let me know what it actually prints?

**Comment by sunderme** [comment]
`message(Begin terminal check)
system($$PKG_CONFIG_EXE "--errors-to-stdout --print-variables qtermwidget5")
message(End terminal check)
isEmpty(TERMINAL):system($$PKG_CONFIG_EXE "--atleast-version 0.9.0 qtermwidget5"){`

**Comment by MeanSquaredError** [comment]
@sunderme 
The variables names look OK (same as on Fedora 31)

Can you please upload your file `qtermwidget5.pc`
IIRC you mentioned that it is in
`/usr/lib/x86_64-linux-gnu/pkgconfig/qtermwidget5.pc`

**Comment by sunderme** [comment]
[pc.zip](https://github.com/texstudio-org/texstudio/files/4397363/pc.zip)

**Comment by MeanSquaredError** [comment]
That is funny - it says `Version: 0.14.1` which is definitely sufficient.
What does `pkg-config --modversion qtermwidget5` print when you run it on your machine?

**Comment by sunderme** [comment]
0.14.1

**Comment by sunderme** [comment]
--atleast-version seems not to give the correct answer, whyever ...

**Comment by MeanSquaredError** [comment]
That's really strange. I guess it is some kind of pk-config bug. Anyway, I will update the PR so that it will use `pkg-config --modversion` as a workaround.

**Comment by MeanSquaredError** [comment]
@sunderme 
I implemented a workaround that uses `pkg-config --modversion` to check if there is a suitable version of `qtermwidget5`. It works correctly on Fedora 31. Please test it on your machine and let me know if it works correctly on your machine too.

**Comment by sunderme** [comment]
that works
 I have pulled it, thanks.

**Pull request merged**
