### PR TITLE
new cwls

### PR DESCRIPTION
**Pull request by mbertucci47**
New cwls for `collcell`, `easyfig`, `gobble-user`, and `storebox`. Updated cwl for `siunitx`.

### CODE REVIEW

**Comment by muzimuzhi** [comment]
Newly added cwl files should be in sub-dir `completion`, while currently they are in root directory.

**Comment by muzimuzhi** [comment]
CI Linux-autoTests fails at
https://github.com/texstudio-org/texstudio/blob/741518b1fce645259f6ff34da3b87875e3771d9a/src/tests/syntaxcheck_t.cpp#L205-L206
`per-mode=reciprocal-positive-first` is [deprecated since siunitx v3.0.0](https://github.com/josephwright/siunitx/blob/main/CHANGELOG.md#deprecated-1) hence the tests should be adapted.

**Comment by mbertucci47** [comment]
Apologies for the misplaced files, now fixed

**Comment by sunderme** [comment]
thanks

**Pull request merged**
