### PR TITLE
"Show Line Numbers" setting improvements

### LINKED ISSUE #804: Line numbering too deep in advanced settings
Enabling line numbers in a fresh TeXstudio installation takes a lot of clicks:
Options -> Configure TeXstudio -> Show Advanced Options -> "OK" -> Adv. Editor -> Show line numbers

Line numbers shouldn't be an advanced setting, especially considering that error messages always report line numbers.

Two suggestions:

* Move "Show line numbers" from "Adv. Editor" to "Editor" in settings.
* Make "All line numbers" the default setting.

### Environment
- TeXstudio: 2.12.16
- OS: all
- TeX distribution: all

### PR DESCRIPTION
**Pull request by thomas-daniels**
Resolves #804 

* Puts "Show Line Numbers" in Editor (rather than Adv. Editor), makes it a 'normal' option rather than an advanced option.
* Makes "All Line Numbers" the default value.

### CODE REVIEW

**Comment by sunderme** [comment]
I am not sure that I want to see line numbers as default ...
I agree with putting the option as non-advanced

**Comment by thomas-daniels** [comment]
@sunderme I can recreate the PR with only the first commit, what's your opinion on that?

**Comment by sunderme** [comment]
> @sunderme I can recreate the PR with only the first commit, what's your opinion on that?

That would be great !

**Comment by thomas-daniels** [comment]
okay, moving to #811

**Pull request closed without merging**
