### PR TITLE
new and updated completion files

### PR DESCRIPTION
**Pull request by mbertucci47**
New cwls for `algpseudocodex`, `algxpar`, `backref`, `btxdockit`, `changebar`, `changepage`, `class-ltxdockit`, `combine`, `dlfltxbcodetips`, `dlfltxbmarkup`, `dlfltxbmisc`, `expkv-cs`, `expkv-def`, `expkv-opt`, `expkv`, `feyn`, `fp-addons`, `fp-basic`, `fp-eqn`, `fp-eval`, `fp-exp`, `fp-pas`, `fp-random`, `fp-snap`, `fp-trigo`, `fp-upn`, `hypcap`, `imakeidx`, `index`, `ltxdockit`, `notespages`, `ntheorem`, `numerica`, `pseudo`, `rerunfilecheck`, `sidenotes`, `statrep`, `tabto`, and `texdimens`.

Updates for `biblatex`, `csquotes`, and `fp`.

### CODE REVIEW

**Comment by sunderme** [comment]
thanks

**Comment by muzimuzhi** [comment]
@mbertucci47 Seems you're adding/reviewing cwls lexicographically. What an enthusiasm!

**Comment by mbertucci47** [comment]
Haha yes, something like that. I suppose there are worse ways to procrastinate than writing cwls

**Comment by Basmah1961** [comment]
Hello,

Thank you for your efforts. In `nicematrix`, could you see why TeXstudio does not support autocompletion when putting the options of the environment after the preamble of the document?

One related topic from TeX StackExchange: [keyvals not recognized from *.cwl file](https://tex.stackexchange.com/questions/600525/keyvals-not-recognized-from-cwl-file)

Regards,
Basmah

**Comment by muzimuzhi** [comment]
@Basmah1961 According to #1334,

> @sunderme: my guess would be that [options%keyval] can't be behind the mandatory arguments for it to work in txs
> [...] and it is unlikely to change

**Comment by mbertucci47** [comment]
There's no problem with `options%keyvals` being the mandatory argument. The problem is that there's not currently support for multiple keyval fields, whether or not they have the same arg specification (also mentioned [here](https://github.com/texstudio-org/texstudio/pull/1930#discussion_r747810837)).

**Pull request merged**
