### PR TITLE
Insert graphics quick improved

### PR DESCRIPTION
**Pull request by tmelorc**
There was an empty item in combo list. I replaced by pt.
Also, changed the text message for caption too tip since it refers to list of figures, not of tables.

### CODE REVIEW

**Comment by tmelorc** [comment]
I don't know if this commit will add the quick array code again or not. Sorry, I'm not sure if I'm committing correctly.

**Comment by sunderme** [comment]
yes, you should create a new branch for a new feature.
You can delete branches once they are included in txs.
Thanks.

**Comment by tmelorc** [comment]
> yes, you should create a new branch for a new feature. You can delete branches once they are included in txs. Thanks.

Oh, sorry. 
So, should I create a branch now and do again the PR or this previous one was ok?
Thanks.

**Comment by sunderme** [comment]
the change is integrated.
This is rather for future contributions.

**Pull request merged**
