### PR TITLE
Small code updates.

### PR DESCRIPTION
**Pull request by fjpereny**

### CODE REVIEW

**Comment by sunderme** [comment]
please don't comment removed code.
remove the comments and describe the changes in the commit message or here

**Comment by sunderme** [comment]
are you going to change the PR ?

**Comment by fjpereny** [comment]
Hi partner, apologies for delay.  I will fix this and update.

**Comment by fjpereny** [comment]
Not sure why it failed on the Mac OS X built, seems to build fine on my machine.  If it is a problem we can just kill this PR, I was just trying to clean up some code.

**Pull request merged**
