### PR TITLE
Enhance TeXdoc dialog

### PR DESCRIPTION
**Pull request by octaeder**
- use package list from CTAN
- show package list as a table
- regExp search filter for package names
- add a button which opens CTAN package doc
- fix enabled open button while testing whether texdoc is available

### CODE REVIEW

**Comment by dbitouze** [comment]
> * regExp search filter for package names

I didn't follow the discussion and have no much time right now but not regExp search on packages descriptions as well?

Anyway, many thanks for such a great improvement!

**Comment by octaeder** [comment]
@dbitouze Thanks for the compliment. Yes, currently the regExp is applied to the name column only. I already thought about searching the caption (this is the ctan notation they use for the headline, the package description is more text). But this needs some more design decisions. When you apply the expr. to both columns you may need to type more until you find your package. Adding a new search field for the caption might look a bit too much for the ui, and you may need options telling how to combine the results (and/or). Or use only one option telling which column you want to search (this could include a third case for "both columns". And this is still not all I need to know.
You may have a look at the lower end of #2848 for an image.

**Comment by sunderme** [comment]
thanks

**Comment by octaeder** [comment]
> > Or use only one option telling which column you want to search (this could include a third case for "both columns".
> 
> @octaeder Would be nice, IMO.

I can create a PR for this:

grafik

**Comment by sunderme** [comment]
the text should search title and description,  no options

**Comment by sunderme** [comment]
you can play around with the result order

**Comment by sunderme** [comment]
Yes

**Comment by octaeder** [comment]
I will not guess what you want

**Comment by sunderme** [comment]
alright

**Comment by octaeder** [comment]
so it's OR

**Comment by octaeder** [comment]
You need to update the tooltip.
Since you always search the description case insensitive, it makes no sense to enter upper case letters in the search field, because the name field searched in fact is the key, which is always in lower case. So a distinction of foundLevel 2 and 3 is useless (s. https://github.com/texstudio-org/texstudio/commit/26d0ede547ff6f9094eddbd110baa6c9be6f7b81).

**Comment by octaeder** [comment]
changing the checkbox doesn't give the appropriate result for the search term (inconsistent)

**Comment by tmelorc** [comment]
I'm using TeXstudio 4.8.2 (git 4.7.1-420-g6872e90d1).
I'd suggest to use smaller window's height.
When I open the Packages Help on my laptop, the window is too tall so that buttons are almost out of screen.

**Pull request merged**
