### PR TITLE
Changes to cwl files and related section in manual

### PR DESCRIPTION
**Pull request by muzimuzhi**
Changes to cwl files:
 - move `\dashbox`, which is valid only inside `picture` latex environment, from `latex-dev.cwl` to `latex-document.cwl`, since other `picture`-only commands are all recorded in the latter cwl file.
 - remove redundant argument of arg-free commands (`\<xxx>name`)
 - set arg-name and classifier for `\(re)newenvironment`
 - add some `%l` to dimension related arguments
 - unify name of arguments
 - other minor changes

Changes to related section in manual:
 - supplement descriptions for `key` and `envname`, according to the related source lines:
https://github.com/texstudio-org/texstudio/blob/6ca046695f953300856c7b817eab5004c40d8460/src/latexpackage.cpp#L676-L677
 - add after-punctuation spaces

### CODE REVIEW

**Comment by muzimuzhi** [comment]
> * set arg-name and classifier for `\(re)newenvironment`

After this change, the following lines of source code might be redundant:
https://github.com/texstudio-org/texstudio/blob/6ca046695f953300856c7b817eab5004c40d8460/src/latexdocument.cpp#L827-L858

This has the similar situation in commit https://github.com/texstudio-org/texstudio/commit/d538bab7c91e9b845e0be698d1aac49b7e9b2d77, which can be traced back to issue #689.

**Comment by sunderme** [comment]
thanks

**Comment by sunderme** [comment]
do you want to be mentioned in about dialog ?

**Comment by muzimuzhi** [comment]
> do you want to be mentioned in about dialog ?

It is my honor. Either "muzimuzhi" or "Yukai Chou" is welcome.

**Pull request merged**
