### PR TITLE
narrow General config

### PR DESCRIPTION
**Pull request by octaeder**
This PR is a cut down of PR #2747 where you can find full details. Change affects page General of Config Dialog:

01_General

### CODE REVIEW

**Comment by sunderme** [comment]
all drop-down above are over the complete width, why should the language selector stick out ?

**Comment by sunderme** [comment]
the shift left of the widgets is okay (still not necessary)

**Comment by octaeder** [comment]
did you read #2747 ?

**Comment by sunderme** [comment]
please, don't refer to a bunch of text and expect me to pick up what part of that you are referring to.
I don't read anything there that states that there is a deeper necessity to keep that drop-down small.

**Comment by octaeder** [comment]
Many of the combo boxes expand to the right so they are very wide. As an example take the language picker of General page. When you click on it then a huge panel opens that takes about three quarters of the page width while the text list takes only a small amount of it.

**Comment by octaeder** [comment]
Even worse is the font combo box that stretches far to the right.

**Comment by octaeder** [comment]
but the latter I did'n fix

**Comment by sunderme** [comment]
yes, that is basically true for all combo-boxes in the in the config.
but why is that bad ? odd maybe.

**Comment by octaeder** [comment]
1. not all combos are full width, so this is not a one exception (s. edit, adv. edit). 2. in most cases the presented list is quite short. So the area is not so large. But the language list combo is really large (with fusion you see the full list). And the fonts display even expands over the right edge of the window.

image

image

This not nice at all.

**Comment by octaeder** [comment]
and if you look close you will notice that the appereance of Font combo boxes (General and Edit) looks different from all others. That's wired.

Why not full width for combos in general? As I pointed out in the first PR there are scrolling issues: When scrolling a page (with the wheel) it becomes likely that such a combo box moves under the mouse pointer. But then the page stops scrolling and the combo box is being scrolled. Thus you might change settings without notice.

**Comment by octaeder** [comment]
even so I don't plan to shrink all combos.

**Comment by octaeder** [comment]
The large extent of the combos could be bad for the user because he has to focus far to the right for moving the pointer to where he can open the list, and then back far the left to read the entries of the list. Much distracting eye movement. But this is not such a problem but only if you are an experienced user who knows that this is not really necessary. One can click anywhere in the combo an the list is opened (at least for fusion and default style). But this is not true for the font combos. So in most cases I agree that the combo can extend to the right edge, but sometimes it should not.

**Comment by sunderme** [comment]
I would much prefer to actually address weaknesses of txs and not pure cosmetics.
the config dialog may be better with small screens and possibly with large screen/fullscreen dialog (and no, I am not talking about moving stuff a few pixels, look at the commands pane).

The fontcombobox seems special, but that is probably a qt issue.
So, there is no argument to just shrink one combobox. The scrolling issue does not go away by moving comboboxes around, even if you do it with all of them.

So, acceptable change: shift the left edge of the combobox.

**Comment by sunderme** [comment]
thanks

**Pull request merged**
