### PR TITLE
Luapreview

### PR DESCRIPTION
**Pull request by octaeder**
Add support for pdfpreview with lualatex (s. #2291). Please check carefully as always, cause I'm not sure if I have done all that is necessary.
configdialog.ui should be updated with a new item in the combobox "comboBoxDvi2PngMode". But I assume that I shouldn't edit the file so someone else has to do it with qt-tool. Otherwise I would add:
```
                <item>
                 <property name="text">
                  <string>Preview with lualatex</string>
                 </property>
                </item>
```
Thx

### CODE REVIEW

**Comment by sunderme** [comment]
Have you tested the code ?
From first glance, it looks like you missed some changes: 
buildmanager.cpp line 2074: ```if (dvi2pngMode == DPM_EMBEDDED_PDF) {``` ...

Any particular reason why you can't use qt designer ?

**Comment by octaeder** [comment]
I can search for the missed lines, there are more. How could I do builds locally (in my fork, branch) when working with github? I don't know qt designer, is it easy to work with?

**Comment by sunderme** [comment]
You should build txs with the changes locally, see wiki.
Usually you clone it locally, make the changes in a new branch, push to your fork and from there you make a pull request.
Depending on your system, qtcreator is the IDE to use which also includes the qt-designer which is easy to use.

Untested code is usually considered as faulty code.

**Comment by octaeder** [comment]
@sunderme I'm working hard on this issue. But still with problems. The new drop down may show part of my progress:
grafik
So to finish this I hope you can help me. Be aware that I don't know anything about C/C++ or oop, I'm sorry.
I have problems with the creation of the fmt file (precomile of lualatex.ini and preamble) that should be created by a first process (s. buildmanager.cpp around l. 1810, compare with my branch luapreview). It ends with "Process exited with error(s)". I can't figure out what errors. The second process is started anyway with lualatex and shows the preview. But it doesn't work with larger examples.

As a result of my work some notes: The creation of the first process can't be handled in the same way as for pfdlatex and latex. These two extract the program (possibly incl. path) from the command definitions in the config (technically from CMD_PDFLATEX and CMD_LATEX), to start it with the -ini option (f. ex. pdflatex ... -ini ...). This will create the fmt file. But for lua it has to be "luatex.exe ... -ini ..." while CMD_LUALATEX uses lualatex.exe (if the user didn't enter somthing different). So I hard coded luatex.exe and assume that it will be found in the path of executables. I could do better if someone could provide code that replaces lualatex.exe by luatex.exe in path\lualatex.exe.

**Comment by sunderme** [comment]
the -ini part is for active precompilation of headers, so that could be skipped for later.
luatex should not be hard-coded, better use the lualatex command and change the actual command (but keeping the path)

**Pull request closed without merging**
