### PR TITLE
make frac, dfrac and sqrt in math menu translatable

### LINKED ISSUE #2995: “Square Root” not translated nor translatable (anymore)
### Describe the feature and the current behavior/state
The string “Square Root” in the math menu should be translatable.
### Who will benefit with this feature?
Any non English speaking user of TXS.

### PR DESCRIPTION
**Pull request by octaeder**
This PR resolves #2995 and makes the following from that menu translatable:

grafik

### CODE REVIEW

**Comment by sunderme** [comment]
was this manually changed ?

**Comment by octaeder** [comment]
yes, sounds like that I should not have done so. How to proceede?

**Comment by sunderme** [comment]
I look into it.

**Comment by sunderme** [comment]
reextracted from source (`texstudio --update-transaltions`)

**Pull request closed without merging**
