### PR TITLE
Convert UTC time to local time in PDFInfoDock.

### PR DESCRIPTION
**Pull request by clerkma**
To fix the mismatch of 'CreationDate' between pdf file and PDFInfoDock.

### CODE REVIEW

**Comment by sunderme** [comment]
is the pdf creation time always stored as UTC ?

**Comment by sunderme** [comment]
> is the pdf creation time always stored as UTC ?

seems like it.

**Comment by sunderme** [comment]
thanks

**Comment by clerkma** [comment]
thanks

**Pull request merged**
