### PR TITLE
Remove duplicate lines in tcolorbox.cwl

### PR DESCRIPTION
**Pull request by muzimuzhi**
This pr is a continuation of 
 - https://github.com/texstudio-org/texstudio/pull/687#issuecomment-520223496, where I found that `tcolorbox.cwl` file is a 40k+ line monster, and 
 - https://github.com/texstudio-org/texstudio/issues/688, where new feature, comma-separated-list like `#keyvalus:\cmdA,\cmdB`, is added

Main changes:
 - Update dependencies caused by different package options, manually.
 - Use new feature to remove duplicate lines automatically, and reduce file to 3k- lines. This [python script](https://gist.github.com/muzimuzhi/70e31826e4efe351ddd03fe1edff3410) is used, and (with minor changes) may be used to do similar things for other cwl files.

### CODE REVIEW

**Comment by muzimuzhi** [comment]
This pr is not finished yet. Since I found there still are many duplicate lines. (sad)

**Comment by sunderme** [comment]
do you feel confident that we can merge this PR ?

**Comment by muzimuzhi** [comment]
Yes, by now this pr is ready for merging.

I have force-pushed to the branch, in which only two things are done:

 * Update package dependencies manually.
 * Remove duplicate keyvales-groups by the updated [python script](https://gist.github.com/muzimuzhi/70e31826e4efe351ddd03fe1edff3410).
    This means, lines
    ```
    #keyvals:\cmdA
    \xx
    \yy
    \zz
    #endkeyvals
    #keyvals:\cmdB
    \xx
    \yy
    \zz
    #endkeyvals
    ```
    are replaced with
    ```
    #keyvals:\cmdA,\cmdB
    \xx
    \yy
    \zz
    #endkeyvals
    ```

**Comment by sunderme** [comment]
thanks

**Pull request merged**
