### PR TITLE
describe loading logs (manual)

### PR DESCRIPTION
**Pull request by octaeder**
follow up of #2785
also reflect change in main menu Idefix

### CODE REVIEW

**Comment by sunderme** [comment]
to be honest, I find the text a bit confusing.
It also rather describes a "trick" to load the log instead of core txs functionality (which simply is not there).
From functionality point of view, a clickable link in the message window would probably suffice.
From manual point of view, I would rather move the section into the wiki, if that is okay with you.

**Comment by octaeder** [comment]
can you keep the change in viewing.md? Or should I make a new PR for that...?

**Comment by sunderme** [comment]
I can keep that change.

**Comment by octaeder** [comment]
ok, thanks.

**Comment by sunderme** [comment]
moved to wiki/tricks

**Pull request closed without merging**
