### PR TITLE
`babel-french` opening quote `\og ` replaced by `\og{}`

### PR DESCRIPTION
**Pull request by dbitouze**
This change mode according to the author of the package's directive.

### CODE REVIEW

**Comment by sunderme** [comment]
thanks

**Comment by dbitouze** [comment]
You're welcome, but I guess I made a mistake: in French, in Options → Configure TeXstudio → Editor, drop-down list "Replace Double Quotes", the string "French Quotes (babel): \og{} \fg{}" isn't translated in French anymore.

**Comment by sunderme** [comment]
needs to be adapted on transifex ...

**Comment by dbitouze** [comment]
> needs to be adapted on transifex ...

OK, done.

**Pull request merged**
