### PR TITLE
Slight improvements in Insert Graphic wizard

### PR DESCRIPTION
**Pull request by dbitouze**
This PR mainly typos for fixes.

BTW, `H` and `!` are IMHO suboptimal practices.

### CODE REVIEW

**Comment by benibela** [comment]
>Override internal parameters LaTeX used for determining `good' float positions.

wikipedia uses uses, too https://en.wikibooks.org/wiki/LaTeX/Floats,_Figures_and_Captions#Figures

**Comment by sunderme** [comment]
do you adapt the PR then a little ?

**Comment by dbitouze** [comment]
Done (I guess).

**Comment by sunderme** [comment]
indeed

**Pull request merged**
