### PR TITLE
add github-issue template

### PR DESCRIPTION
**Pull request by Piraty**
I really liked to see your project moved to github.
And now that you're here, you face a flood of issues opened.

So standardizing the information users present, i made a minimal issue template that might be worth using instead of asking users the same questions over and over.

If you have better ideas, i'm open to change the PR.

also, see [*here*](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

### CODE REVIEW

**Comment by sunderme** [comment]
what is the "how to solve" part for ?
The rest is quite good.

**Comment by Piraty** [comment]
With "how to solve" i thought of possible code to fix it, i can drop that if that's fine with you.

**Comment by sunderme** [comment]
I think for the usual issues, no one will provide code to solve the issue. That is rather for pull-requests.
So, in my opinion, just remove that part and everything is fine.

**Comment by Piraty** [comment]
done.

**Comment by sunderme** [comment]
merged, thanks

**Comment by dbitouze** [comment]
Nice idea. Nevertheless:

-  is it supposed to look as it currently looks:
capture du 2018-03-15 22-23-59
- there are some typos
- in the same vein: https://github.com/retorquere/zotero-better-bibtex/issues/new which renders e.g. as https://github.com/retorquere/zotero-better-bibtex/issues/925.

**Comment by Piraty** [comment]
@dbitouze  In regard to your references: ofc markdown wan be used.
I recently contributed to a project that used the html-style comments, which i liked. (note that they don't appear in the preview, so they act as instructions for the user opening that issue).
about: typos: yeah... now it's merged. sorry @sunderme

**Comment by dbitouze** [comment]
>note that they don't appear in the preview, so they act as instructions for the user opening that issue

That's the point: currently, the HTML source does appear as is (see the screenshot above), at least on Linux with e.g. Firefox 52.6.0 and Chromium 62.0.3202.94.

**Comment by Piraty** [comment]
> That's the point:  <...>

yes, that **is** the point. when composing the issue's text, user should see the comments  and use them as guideline. when you click `preview` they disasppear, becaue of the nature of comments...

**Comment by dbitouze** [comment]
Indeed they disappear but what is important is the first impression. Currently, the type area looks very cluttered and not very friendly.

**Comment by Piraty** [comment]
if that is your impression, so be it. mine is different, in that i see what i have to do and possibly replace the comments.
Afterall, @sunderme seemded to like it.

If you have a better approach, you are free to open your own PR and have discussion about it.

**Pull request merged**
