### PR TITLE
More completions for siunitx command options.

### PR DESCRIPTION
**Pull request by ElieGouzien**
I added lot of command option for `siunitx.cwl`.
Some allowed options have not been included where they have no effects.

Full list of option has been set for \sisetup ; for the other commands
only the relevant subset has been kept.

Supported siunitx version : 2.8b

### CODE REVIEW

**Comment by MeanSquaredError** [comment]
Seems to mess up a couple of `SyntaxCheckTest::checkkeyval` tests. I guess these tests will need adjustments.

**Comment by muzimuzhi** [comment]
BTW, cwl now supports syntax `#keyvals:\cmd[,\cmd]*`. For example, you can use `#keyvals:\ang,\num,\anotherCmd`. This makes cwl file more compact.

**Comment by ElieGouzien** [comment]
> BTW, cwl now supports syntax `#keyvals:\cmd[,\cmd]*`. For example, you can use `#keyvals:\ang,\num,\anotherCmd`. This makes cwl file more compact.

Good to know! Can we define options for a single command in different `#keyvals` sections ? Typically here I would need to group options in `#keyvals` sections looking to something like `#keyval:\num,\SI`, `#keyval:\si,\SI`…

**Comment by muzimuzhi** [comment]
> Can we define options for a single command in different #keyvals sections ?

Yes

**Comment by sunderme** [comment]
I think the lines 'math-sf=#*' is probably unintentional incorrect.
In context of key/vals it means that only "*" is a valid option (that why one of the test fails).
I suppose it was meant to say "unusual" command, which is not defined in this context, i.e. for key/vals.

**Comment by ElieGouzien** [comment]
It should be better now, and also easier to maintain; I grouped all the options by section of the documentation and never repeated anyone.
If you want I can squash last commit into the first one (to avoid +1000 lines in the history).

> I think the lines 'math-sf=#*' is probably unintentional incorrect.
> In context of key/vals it means that only "*" is a valid option (that is why one of the test fails).

Exact and corrected, except that what made failing the test was rather to have comments between `keyvals` and `endkeyvals` (what might not be really convenient).

**Comment by sunderme** [comment]
Thanks 👍

**Comment by muzimuzhi** [comment]
> Exact and corrected, except that what made failing the test was rather to have comments between `keyvals` and `endkeyvals` (what might not be really convenient).

@ElieGouzien After #1143, I think using comments between `#keyvals` and `#endkeyvals` is now supported (so there is no need to split keyvals into groups). Welcome to test, if you could [compile from source](https://github.com/texstudio-org/texstudio/wiki/Compiling) or after the next alpha/beta release of 3.0.0.

**Comment by ElieGouzien** [comment]
Nice that you fixed this! A 10 s check indicates that it's now OK.

I don't think I will modify this pull request, since the split is also needed because each options section has a specific set of commands for which they have  non-trivial effect, but anyway it's a valuable improvement.

Maybe documenting the several command options (`#keyvals:\cmd[,\cmd]*`) would also be really useful.

**Comment by muzimuzhi** [comment]
> Maybe documenting the several command options (`#keyvals:\cmd[,\cmd]*`) would also be really useful.

The user manual released with texstudio v2.12.18 or newer already contains
> `#keyvals:<command[,command,...]>` (at start of line)

https://github.com/texstudio-org/texstudio/blob/6ff4aa3bb043155edad8114a36e36fd3b804fde6/utilities/manual/usermanual_en.html#L1579
which is added in https://github.com/texstudio-org/texstudio/commit/18ed1a2fbc07f07f600a715a131b96ee8b420b64 (Aug 2019). 

The problem is that the online user manual hosted on [sourceforge](http://texstudio.sourceforge.net/manual/current/usermanual_en.html) is outdated. This has been reported in #593 (May 2019).

**Pull request merged**
