### PR TITLE
#2672 – Add support for drag-dropping & copy-pasting spreadsheets from LO Calc

### PR DESCRIPTION
**Pull request by geolta**
This implements the functionality to drag-drop and copy-paste fragments of spreadsheets from LibreOffice Calc to TexStudio. Support for Excel is currently not supported, as well as complex formatting.

### CODE REVIEW

**Comment by sunderme** [comment]
I`d assume that `\begin{tabular}{cols}...\end{tabular}` is also automatically inserted ?

**Comment by geolta** [comment]
No, the tabular environment is not inserted. I did it this way to make it easier to combine multiple table fragments as it is usually done (at least in my experience where you join several parts of a table).

**Comment by sunderme** [comment]
In my opinion, that is probably a bit unexpected for the user.
I will look into it.

**Comment by geolta** [comment]
Hi, do you already had a look into it?

Thanks :)

**Comment by sunderme** [comment]
My idea would be to check if content into an existing table and act accordingly.
I have not yet started to implement that.
For now, I will prepare the next release.

**Comment by sunderme** [comment]
implemented for paste 
if no table is already present, call table waizard

**Pull request closed without merging**
