### PR TITLE
+84 dictionaries for easy use in TexStudio with Licenses

### PR DESCRIPTION
**Pull request by ZurMaD**
Adding more dictionaries
Dictionaries from Hunkspell
Files(261MB) taken from:
https://github.com/wooorm/dictionaries
Licences:
https://github.com/wooorm/dictionaries#dictionaries-1
GPT-2 
GPT-3 
Apache 2 
MIT

Related:
#1241 #462

### CODE REVIEW

**Comment by sunderme** [comment]
hmm, as enticing as it is, it increases the size of the binary/installer probably quite significantly
how large are the files ?

**Comment by sunderme** [comment]
klingon ?

**Comment by ZurMaD** [comment]
All files around 261MB in total, the idea is to select the most used, not like Klingon haha.

**Comment by sunderme** [comment]
so, any suggestions on how to proceed ?

**Comment by ZurMaD** [comment]
Uhmm I think, first to select the most spoken languages.
image

https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers

So If I select, the proposal list will be:

pt_PT: Portuguese
pt_PT2: Portuguese (Portugal)
ru_RU: Russian
tr_TR: Turkish
ko_KO: Korean
German variations: de_DE + de_AT de_CH
Spanish variations: es_ES + es_MX es_CO es_ES es_AR es_PE es_VE es_CL es_EC es_GT ...
Vietnamese: vi_VI

In case of spanish, IEEE is doing a good work trying to move scientists & researchers from MS Word to Latex. And the list of variations (!='es_ES') is sorted by population per country. 

image
https://en.wikipedia.org/wiki/List_of_countries_where_Spanish_is_an_official_language

**Comment by sunderme** [comment]
I think that I would prefer a mechanism to download dictionaries from the internet, internet then being the our github repository.
alternatively the windows installer could be extended to allow customization.
Download size is not that much of an issue as it used to be but still ...
Do you want to look into that ?

**Comment by sunderme** [comment]
so , I pull the request, but then we have to see what to do about the installers

**Comment by ZurMaD** [comment]
I think it's a good idea `a mechanism to download dictionaries from the internet` but how we can deal with it? in which language will be written? or how to implement inside TexStudio or can be executed like an extension

**Comment by sunderme** [comment]
the win installer is now 140 MB large instead of 90 MB. I think that is acceptable.
However the internal language selector needs to get more usable to handle that number of languages ...

Windows installer is nsi (nullsoft installer), otherwise things need to be integrated directly into txs with c++-

**Comment by MeanSquaredError** [comment]
The Nullsoft installer uses their own scripting language. The language itself does not seem to support downloading external files, but it supports plugins and Nullsoft has a plugin that allows downloading external files:
https://nsis.sourceforge.io/Builtin_NSISdl_plug-in

However it is a solution just for Windows. I am not sure how the various Linux distros will handle the issue (short of just bundling everything into one big package).

For example the .rpm based ones, might offer the package for the base program and multiple additional packages for the different languages or groups of languages. E.g.
```
texstudio-3.x.x.rpm
texstudio-3.x.x-English.rpm
texstudio-3.x.x-French.rpm
texstudio-3.x.x-German.rpm
texstudio-3.x.x-Italian.rpm
...
```
That's the approach they usually take with large ecosystems that would be too big to ship as one package (e.g. Python, PHP, etc.)

**Comment by sunderme** [comment]
for linux, i would not bother. If possible, system hunspell should be used and then the dictionaries need to come from the system
at the moment, only osx dmg needs to be adapted (it seems)

**Pull request merged**
