### PR TITLE
Make "tex.cwl" contain full list of tex primitives and plain tex commands

### PR DESCRIPTION
**Pull request by muzimuzhi**
This pr follows the discussion in #751 .

Main changes:
 - Manually review `tex.cwl`, make it contain _full list_ of tex primitives and plain tex commands.
 - Remove duplicates in other cwl files, resulting the `latex-mathsymbols.cwl` nearly empty.
 - Delete `latex-mathsymbols.cwl` and clear codes using it.

When reviewing, I take the list in [_TeX for the Impatient_](https://www.gnu.org/software/teximpatient/), Chap. 13 as the main reference.

### CODE REVIEW

**Comment by muzimuzhi** [comment]
Some lines originally in `tex.cwl` is not found in the mentioned list used as main reference. Here is a detailed record of where these lines go.

------
Should been added but missing in list. Added to part 3 of `tex.cwl`.
 - missing delimiter of parameter: `\columns`
 - missing primitive: `\patterns`
 - missing commands: `\centering`, `\footins`, `\footnoterule`, `\interdisplaylinepenalty`, `\interfootnotelinepenalty`, `\joinrel`, `\leavevmode`, `\removelastskip`, `\topins`

Not in plain tex, but in latex2e.
 - `\fill`, `\tracingfonts`, and `\unitlength`, added to `latex-dev.cwl`
 - `\protect` and `\raggedleft`, added to `latex-document.cwl`

Not in plain tex and latex2e, but used in texbook. Safely removed from `tex.cwl`.
  - `\allowhyphens`, Appx. D: Dirty Tricks
  - `\closing`, `\danger`, and `\margin`, Appx. E: Example Formats,
  - `\dash`, Exercise 6.6
  - `\ifundefined`, Exercise 7.7
  - `\raggedcenter`, Exercise 14.34

Not found in plain tex, latex2e and texbook. Safely removed from `tex.cwl`.
 - `\annotations`
 - `\ifdefined`, possibly the one defined by `etoolbox` pacakge
 - `\vfilll`

**Comment by MeanSquaredError** [comment]
The build with QT=qt5 seems to fail because the TXS tests fail (QT=qt5 is the only build where we run the tests). And the tests fail because of the two of the TXS completer tests 

`FAIL!  : LatexCompleterTest::simple(smbll cmd +pc) '(ist)==(text)' returned FALSE. (equal failed: got \">>\\b{<<\" !=expected \">>\\b{}<<\" )`
`   Loc: [src/tests/latexcompleter_t.cpp(313)]`
`FAIL!  : LatexCompleterTest::simple(smbll cmd +ec+pc) '(ist)==(text)' returned FALSE. (equal failed: got \">>\\b{<<\" !=expected \">>\\b{}<<\" )`
`   Loc: [src/tests/latexcompleter_t.cpp(313)]`

@muzimuzhi I will send a PR to your branch  muzimuzhi:cwl-tex with the fixed tests.

**Comment by MeanSquaredError** [comment]
@muzimuzhi 
OK, I sent you a PR in your repository that should fix the latexcompleter tests. Merge it and this should take care of the failing build.

**Comment by muzimuzhi** [comment]
@MeanSquaredError 
Many thanks!
I should have pasted the log of test failing since I might be the first one who spotted the failing yesterday (and traced the related log lines).

**Comment by sunderme** [comment]
thanks

**Pull request merged**
