### PR TITLE
Update French translations

### PR DESCRIPTION
**Pull request by dbitouze**
BTW, the changing line numbers are very annoying: they often lead to impossible automatic merge and I didn't find another solution than deleting my TXS' fork, fork again, clone, launch `linguist` with the new `texstudio_fr.ts` file and (hopefully possible) open also the old one I set aside in order to not have to rewrite all the missing translations.

### CODE REVIEW

**Comment by sunderme** [comment]
lupdate should take care of it. Anyway changing line numbers are impossible to avoid.

**Comment by sunderme** [comment]
if you used https://www.transifex.com/texstudio/texstudio , things would be simpler (for me). All other translations come from that site, German included.

**Comment by dbitouze** [comment]
>lupdate should take care of it.

However, I always run it before running `linguist`.

>Anyway changing line numbers are impossible to avoid.

Sigh...

**Comment by dbitouze** [comment]
>if you used https://www.transifex.com/texstudio/texstudio , things would be simpler (for me). All other translations come from that site, German included.

OK, I'll try to use it, though suggestions seems to work better with `linguist`. Could you please upload my last translations to `transifex`?

**Comment by dbitouze** [comment]
Another advantage of `linguist` (over `transifex`) is that, when appropriate, it displays the dialog windows and hence the context, which is sometimes necessary for right translations.

**Comment by sunderme** [comment]
your translation has been uploaded to transifex

**Comment by dbitouze** [comment]
I proceed to a `git pull` for TXS 2.12.12 and run:
```bash
texstudio --update-translations && lupdate texstudio.pro && linguist translation/texstudio_fr.ts
```
in order to see if there were new strings to translate. There was one ("Babel") so I went to [transifex](https://www.transifex.com/texstudio/texstudio/translate/#fr/texstudio_ents/60319933) but it said there is 0 strings that are not translated.

**Pull request merged**
