### PR TITLE
new and updated cwl files

### PR DESCRIPTION
**Pull request by mbertucci47**
Updated `mnsymbol` and made name lowercase; updated `microtype`, `todonotes`, and `unicode-math`; added `comicneue`, `dejavu-otf`, `domitian`, `fdsymbol`, `firamath-otf`, `fourier-otf`, `knowledge`, `logix`, `macrolist`, `mathcommand`, `pst-xkey`, `raleway`, `sourcecodepro`, `sourcesanspro`, `sourceserifpro`, `xkeyval`, and `xkvview`.

### CODE REVIEW

**Comment by sunderme** [comment]
Hmm, why did you change MnSymbol to lower case ? 
I see that the style is called MnSymbol.sty and at least on Linux, you can't use ```\usepackage{mnsymbol}```

**Comment by mbertucci47** [comment]
Interesting, I did not know that package names were case sensitive depending on the operating system. On Windows, `\usepackage{mnsymbol}` works identically to `\usepackage{MnSymbol}`, however with the former, TeXStudio does not recognize `MnSymbol.cwl` which is why I changed it. Do you suggest changing it back to `MnSymbol.cwl`?

**Comment by sunderme** [comment]
yes please
(Windows file system is case insensitive, all others are case-sensitive)

**Comment by mbertucci47** [comment]
Gotcha, should be good now

**Comment by sunderme** [comment]
thanks

**Pull request merged**
