### PR TITLE
Add the ?p command-line expansion that searches for compiled PDF file

### PR DESCRIPTION
**Pull request by MeanSquaredError**
This pull request implements the feature request from https://github.com/texstudio-org/texstudio/issues/754

Basically it adds the ?p command-line expansion which expands to absolute pathname of the PDF file. The file name of the PDF file is taken from the basename of the main .tex file with .pdf appended to it.
The searched directories are the directory that contains the main .tex file plus the additional PDF search directories.

I tested the patch and it seems to be working OK.

That being said, I am not sure that the selected design decision is correct. 

A) This pull request implements the ?p expansion for .pdf files, but TexStudio can also generate .ps or .dvi files (or any other image type for that matter). So while ?p solves the problem with .pdf files, it does not solve the problem with the other image types.
B) We can only search for files with the same basename as the main .tex file. What if someone compiles PDF files with some other name?

I can think of several possible workarounds that can be implemented in code:

1. Add the file extension in braces, e.g. ?p{pdf} or ?p{dvi} or ?p{ps} , etc. This solves the problem A (file extensions other than .pdf) but does not solve the problem with other filenames.

2. Use a new, third expansion syntax (besides % and ?). For example we could use expansions enclosed in { and } and inside them allow the following expansions:
%% is the % character
%b is the main file basename
%e is the main file extension
For example, let's say that we compile our tex files by adding the -compiled suffix to them and setting the extension .pdf. Then main.tex would be compiled to main-compiled.pdf

Then our command would look like this:

xdg-open {%b-compiled.pdf} > /dev/null

3. Maybe there is some other way to design the expansions so that they would allow solving problems A and B.

I am still unsure of the correct approach, so any comments, thoughts or suggestions are welcome.

### CODE REVIEW

**Comment by benibela** [comment]
There is the colon prefix syntax to get paths to other files than the main file. e.g. `?c:a` to get the absolute path to the current file.

There `p:` for the pdf could be added and then you can do `?p:a` or `?p:ame` ...

**Comment by MeanSquaredError** [comment]
Yes, I was thinking of using p: to specify search for pdf file, that is a file with the same basename as the main file and extension .pdf

Then I thought that we probably want to use the same approach for the DVI and PS viewers too. 
So the question is how to specify the expansion for DVI and PS files?
Maybe use expansions like 
?p:am.dvi
?p:am.pdf
?p:am.ps
This would imply that the ?p:am expansion would have to look-ahead the following extension on the command-line(.dvi .pdf .ps) and to modify the search so that it would look for a file with the extension that follows after ?p:am

**Comment by MaxSagebaum** [comment]
I do not know how hard the look-ahead would be to implement. From a documentation and readability perspective it would be quite hard to understand since it is the only command that uses this kind of functionality. Especially if the creation script creates some additional files based on the output pdf name.

Then you would have for a dependency file: ?p:am.pdf.d

If you would like to add a postfix this would look like ?p:am)-depend.pdf. Here, the look-ahead would need to look over '-depend' to find the prefix.

If you have some other dot in there ?p:am.gen.pdf the 'p' command would look for a '.gen' file which might not exist.

Therefore I would vote for ?p{pdf}:am.pdf which uses pdf two times but would make it clear that 'p' searches for a pdf file or any other file extension the user can then specify

**Comment by benibela** [comment]
There is also already some kind of full search, when you use `*` in the  name. Although that has the issue that it is searched before running any commands, so on the first compilation, when there is only the tex, it will not find any file, and thus not run anything.

**Comment by MeanSquaredError** [comment]
@benibela Yes, I looking at the code and noticed both the c: modifier and the * character which enables full search. Now the question is how to combine all these things together without breaking anything.

The way I see the new functionality it must fulfill the following requirements:

1. Don't break any existing settings. After adding the new code TXS must keep working the same way with any existing settings that users have configured so far.
2. The new expansion characters must be easily understandable for users other than the developers who wrote the code.
3. The new code must be easily maintainable.
4. The new expansion characters must be flexible enough. At the very least they must work not only for .pdf but also for other extensions like .dvi and .ps

Almost impossible task :-)

Anyway, after giving it a bit of thought I would say that IMHO the best new syntax is :

?p{pdf}:am.pdf or the equivalent ?p{pdf}:ame

Here is how I imagine it should work:

1. Generic syntax should be ?p{ext}:am.ext or ?p{ext}:ame
2. The system would allow expansion modifiers c: and p{ext}:
without a modifier it will select the master file (as it does now).
with c: it will select the current file (as it does now)
with p{ext} it will do the following:
A) It will build a filename consisting of the master basename and .ext as an extension.
B) It will search the master directory and the additional PDF search directories for the filename built in A.
C) If a matching file is found, then its absolute pathname will be selected for further processing. If no matching file is found we can either select some reasonable default (e.g. basename.ext in the master file directory) or generate an error.
3. If will do the pathname expansion like it does normally using the remaining letters but using the found absolute pathname from 2 instead of the current or master .tex file.

So with this semantics the proper way to reference the generated .pdf file will be :

?p{pdf}:am.pdf or the equivalent ?p{pdf}:ame
(I prefer the second syntax but the first one will work too).

It will be at least 3-4 days until I find the time to implement these changes, so if anyone has any comments or ideas, you are welcome to give ideas.

**Comment by MeanSquaredError** [comment]
Changed the expansion to ?p{ext}: as per the discussion above. Please do not merge yet, because I still need to add the explanation on the Configure/Commands screen and to add a simple test.

**Comment by MeanSquaredError** [comment]
OK, I added an explanation about the ?p{ext}: file selector on the configuration dialog and also added a simple test for that selector. So I think the PR is suitable for a review (and possible inclusion into the source tree if it is good enough).

I also added a comment into the source code documenting the idea for another file selector (in case ?p{ext}: is not flexible enough). I will copy&paste it here:

`TODO: If selector ?p{ext}: is not flexible enough then maybe we should implement another selector:`
` ?f{regexp_with_basename}:`
` It will be processed like this:`
` 1. regexp_with_basename undergoes %-token replacement`
`    %m is replaced by the complete basename of the master file.`
`    %% is replaced by %`
` 2. The expression from 1 is used to search the master file directory, the current file`
`    directory and the extra PDF directories.`
` 3. If step 2 finds a matching file it is used as a selected file. If step 2 does not`
`    find a file, then some reasonable default is used.`

**Comment by sunderme** [comment]
thanks
the manual would need an update ...

**Comment by MeanSquaredError** [comment]
@sunderme , @timhoffm , @benibela 

I thought about documenting the ?p option in the manual too after I added the code but could not find the manual source code anywhere. I guess I am missing something obvious, but can you please point me to the URL where the manual source is located? If it is not available in a repository then I can just send you the proposed changes in the documentation as plaintext.

**Comment by sunderme** [comment]
it is in the repository under utilities/manual/…

**Pull request merged**
