### PR TITLE
Added 3 more themes to the Beamer wizard

### PR DESCRIPTION
**Pull request by JackHack96**
I've added 3 modern themes to the Quick Beamer wizard.

### CODE REVIEW

**Comment by sunderme** [comment]
thanks

**Comment by homocomputeris** [comment]
Is it possible to fetch the list of installed themes from the disk?

**Comment by muzimuzhi** [comment]
@homocomputeris Which list, the list of installed latex beamer theme, or the list of themes in beamer wizard of texstudio? If it's the first list, then here, the repo of a latex editor, is not the right place to ask. 

PS: You could (or should) consider posting a new issue.

**Comment by homocomputeris** [comment]
I mean, can't TXS get the list of beamer themes from the disk instead of relying on the hardcoded one? (It's not a reason for an issue, just curiosity)

**Pull request merged**
